### ISSUE TITLE
Problema utilizando UbeeSDK

### ISSUE THREAD

**Issue by andersonlucasg3** [In-Loco-Media/inlocomedia-ios-sdk#1]
Estou implementando sua API em um projeto.

Fiz a implementação baseada na documentação, a única diferença é que estou utilizando Swift como linguagem padrão. Mas percebi que a documentação está desatualizada, alguns métodos não existem mais no SDK e outros foram alterados.
Estou tentando utilizar apenas a funcionalidade de ad por notificação.
Segue abaixo imagem com o erro/exceção no log e parte da implementação.

![captura de tela 2015-03-26 as 18 50 24](https://cloud.githubusercontent.com/assets/1627653/6858015/ed1ddcf6-d3e9-11e4-8dad-c4a85d7ff7ca.png)

**Comment by vitormf** [comment]
Olá Anderson,

Obrigado pelo interesse em usar o SDK de ads da In Loco Media.

A funcionalidade de Notification Ads está desabilitada na versão atual (1.5).
Estamos realizando alterações nesta funcionalidade, que deverão entrar no próximo release.

No entanto, devemos ressaltar que o Notification Ads não deve ser usado para monetização de uso geral.
Para isso recomendamos utilizar Display Ad e/ou Interstitial Ad.

O uso do Notification Ads deve ser feito quando o publisher realiza eventos/campanhas internos no seu app.
Neste caso, você precisaria criar esta campanha, com o target, no nosso serviço.
Este serviço está em BETA e caso o publisher tenha interesse, deverá entrar em contato com monetization@inlocomedia.com

**Comment by vitormf** [comment]
O SDK foi atualizado. Na versão 1.5.2 o Notification Ads pode ser usado normalmente.

Por favor referenciar a documentação atualizada:
https://github.com/In-Loco-Media/inlocomedia-ios-sdk/wiki/Notification-Ads
