### ISSUE TITLE
Problema na instalação do SDK

### ISSUE THREAD

**Issue by macecchi** [In-Loco-Media/inlocomedia-ios-sdk#2]
Boa tarde!

Estou instalando o SDK, adicionando o pod (2.0.0) e os arquivos extras para a mediação do DFP, mas, ao compilar, uma biblioteca está faltando. Não encontra nem na arquitetura dos devices nem do simulador.

Tentei instalar também usando o Framework diretamente, mas o [link direto](https://s3.amazonaws.com/mobile-api/IOS/v2/Release+Files/2.0.0/InLocoMediaAPI-2.0.0.zip) está dando Permission Denied. 

> ld: framework not found UbeeAPI for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by falconegabriel** [comment]
Olá Mario, 

O problema foi corrigido. 
Os links estavam apontando para uma versão incorreta. 
Peço desculpas pela inconveniência. Pode usar o cocoapods normalmente. 
O link para download dos arquivos de mediação podem ser encontrados nas páginas de mediação e no link abaixo:
- [Mediação AdMob/DFP](https://s3.amazonaws.com/mobile-api/IOS/v2/Release+Files/2.0/2.0.0/InLocoMediaAdMobAdapters-2.0.0.zip)

Qualquer outra dúvida é só perguntar, 

Abraços,

**Comment by macecchi** [comment]
Era isso mesmo o problema. Estava usando os arquivos de mediação da versão antiga. 

Agora foi. Obrigado! :)

**Comment by macecchi** [comment]
Opa @gafm, uma dúvida. O 'ads key' usado na inicialização em `[options setAdsKey:@"<your_ads_key>"];` seria o App ID encontrado na tela do app no dashboard? A documentação não deixa isso claro.

**Comment by rfccg** [comment]
É isso mesmo @macecchi!

**Comment by macecchi** [comment]
Ih, tive mais um problema aqui. Agora que vi que o build está gerando este warning:

`ld: warning: ignoring file libInLocoMediaAdMobAdapters.a, missing required architecture arm64 in file libInLocoMediaAdMobAdapters.a (2 slices)`

Usando o `lipo -info` dá pra ver que realmente não tem todas as arquiteturas:

`Architectures in the fat file: libInLocoMediaAdMobAdapters.a are: armv7 x86_64`

**Comment by rfccg** [comment]
Olá @macecchi, mais uma vez pedimos perdão. 
O problema foi corrigido. Pode baixar novamente o [**InLocoMedia Adapters Library**](https://s3.amazonaws.com/mobile-api/IOS/v2/Release+Files/2.0/2.0.0/InLocoMediaAdMobAdapters-2.0.0.zip) e adiciona-lo ao seu projeto.

**Comment by macecchi** [comment]
Obrigado :)
PS: Por que não fazer um cocoapod desses adapters também?

**Comment by rfccg** [comment]
Isso está no pipeline e será feito em breve!
