### ISSUE TITLE
Crash no App

### ISSUE THREAD

**Issue by monteiro-luiz** [In-Loco-Media/inlocomedia-ios-sdk#3]
Fiz todas as recomendações. No appdelegate o app crasha.

2016-10-22 11:36:25.833673 Relive[4486:1574107] [DYMTLInitPlatform] platform initialization successful
2016-10-22 11:36:26.963426 Relive[4486:1573984] InLocoMedia: Initializing... v2.2.1
2016-10-22 11:36:26.976939 Relive[4486:1573984] +[ILMDefaults locationEnabled]: unrecognized selector sent to class 0x100379db0
2016-10-22 11:36:26.979547 Relive[4486:1573984] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[ILMDefaults locationEnabled]: unrecognized selector sent to class 0x100379db0'
**\* First throw call stack:
(0x1936481c0 0x19208055c 0x19364f1b8 0x19364c278 0x19354659c 0x1001a0d20 0x1001a0c6c 0x1001a550c 0x1001a53c0 0x100189614 0x1008c521c 0x1008c604c 0x10018944c 0x10002f750 0x19950342c 0x199713b70 0x1997198e0 0x19972e080 0x1997168c4 0x1951e98bc 0x1951e9728 0x1951e9ad0 0x1935f6278 0x1935f5bc0 0x1935f37c0 0x193522048 0x1994fc5dc 0x1994f7360 0x10002fa98 0x1925045b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

Justamente na linha do "init" da InLoco >>  [InLocoMedia initWithOptions:options];

**Comment by rfccg** [comment]
Olá Luiz,
Você fez a integração via Pods ou colocando o '.framework' manualmente? 
Se fez colocando o framework manualmente, acho que você esqueceu de colocar a flag -ObjC no 'Other linker Flags' do  Build Settings. 
Acho que nosso README está realmente faltando esta informação mas ela consta na documentação [aqui](https://github.com/In-Loco-Media/inlocomedia-ios-sdk/wiki/Getting-Started).

Por favor se o problema persistir não hesite em nos contatar. Atualizarei os README com essa informação em breve.

**Comment by monteiro-luiz** [comment]
Fiz manualmente, coloquei a Flag e funcionou na primeira vez que rodei, quando rodei a segunda começou a dar isso. Desde então não consigo mais executar o código com o essa linha no AppDelegate >> [InLocoMedia initWithOptions:options];

**Comment by rfccg** [comment]
Eu vi que você mandou para @dudupires , algum erro relacionado com bitcode, esse erro se mantém ou o único erro é este que você mandou aqui? Caso ele se mantenha, poderia mandar uma descrição do dele aqui?
Você usa CocoaPods ou Carthage? Existe a possibilidade deles sobrescreverem essa flag.
Você poderia tentar refazer os passos? Desinstalar o app, dar clean, verificar que a flag está adicionada como na foto abaixo e dar build. Caso funcione tente rodar uma segunda vez ver se o erro persiste. 

![screen shot 2016-10-24 at 1 09 16 pm](https://cloud.githubusercontent.com/assets/17709209/19653659/b8a312f6-99eb-11e6-9c68-764ebb5a40fa.png)

Esse erro que você mandou aqui, acontece pois o Xcode não conseguiu carregar o uso de categorias que fazemos e a flag é justamente para resolver esse problema. Eu repliquei este erro apenas removendo a flag, e ao adiciona-la novamente volta a funcionar normalmente.

**Comment by monteiro-luiz** [comment]
O bitcode é na hora de mandar para a loja! Ele não compila o archive!

**Comment by monteiro-luiz** [comment]
Vou refazer os passos desinstalando tudo para ver o que acontece! Se bem que fiz isso no Other Linker Flags. Limpei ela buildei e refiz mas não deu em nada.

**Comment by rfccg** [comment]
Avaliei aqui a parte do bitcode. Vai no Build Settings e muda o valor da flag 'Enable Bitcode' para NO e o archive vai funcionar. Vou atualizar a documentação, e vamos averiguar como mudar contornar esse problema para não precisar alterar esta flag em futuros releases.

**Comment by monteiro-luiz** [comment]
@rfccg Ok! Vou iniciar o processo inteiro e te aviso! Obrigado!

**Comment by monteiro-luiz** [comment]
@rfccg limpei o projeto inteiro! Refiz todos os passos! Continua a mesma!
![captura de tela 2016-10-24 as 18 53 32](https://cloud.githubusercontent.com/assets/19490821/19665400/3ca13c7a-9a1b-11e6-8426-75b80bc925c0.png)

**Comment by rfccg** [comment]
Tu pode me mandar um print da parte de Linking do Build Settings? Eu quero comparar com o nosso pra ver se consigo reproduzir teu cenário. Tipo essa aqui em baixo

![screen shot 2016-10-24 at 7 07 30 pm](https://cloud.githubusercontent.com/assets/17709209/19665800/37d2f1fa-9a1d-11e6-8ae3-a3651ad7516f.png)

Enquanto isso vou continuar olhando aqui se existe alguma outra razão fora a flag '-ObjC' para da falha no carregamento das categorias.

**Comment by monteiro-luiz** [comment]
Adicionei o -ObjC no TARGET e no PROJECT e funcionou! Vi que na parte de TARGET ele não estava colocando nada e testei para ver e funcionou!

**Comment by rfccg** [comment]
Otimo! :D
