### ISSUE TITLE
Duplicate symbols - CocoaSecurity - SDK 2.3

### ISSUE THREAD

**Issue by macecchi** [In-Loco-Media/inlocomedia-ios-sdk#4]
Fui atualizar do SDK 2.1.x para a versão 2.3.0 e tive problemas na compilação do meu app.

Parece que vocês incluíram no framework a biblioteca CocoaSecurity. Como eu também já importo essa biblioteca no meu projeto usando o CocoaPods, na compilação havia diversas mensagens de erro de "duplicate symbols". Acho que é só questão de vcs declararem a dependência dela no podspec ao invés de embutir o código direto dentro do framework, e deixar o CocoaPods importar ela na instalação.

Tentei atualizar pra versão 2.2.1 e funcionou.

**Comment by rfccg** [comment]
Olá Mario Cecchi,
Obrigado pelo aviso.
Faremos um hotfix e lhe avisaremos assim que estiver disponível.

**Comment by rfccg** [comment]
Olá Mário,
O problema já foi resolvido. Tente usar a versão 2.3.1

Obrigado pela colaboração.
