### ISSUE TITLE
Umbrella header for module 'InLocoMediaSDKEngage' does not include header

### ISSUE THREAD

**Issue by htrcarlos** [In-Loco-Media/inlocomedia-ios-sdk#5]
Every time I build my project for the first time, these errors below are shown:

![screen shot 2018-05-07 at 15 32 54](https://user-images.githubusercontent.com/1573615/39721036-2b9e2dca-520c-11e8-90da-f3004accd0fe.png)

The next builds are succeeded with no errors related to the framework. This is problem is still ok for development, but a big problem considering continuous integration.

This is happening in the latest stable version, 3.5.6 (and was already happening in the previous version).

Any help would be great!
Thanks!

**Comment by marcelscr** [comment]
Hello @htrcarlos,

thanks for reporting the issue. We just released a hotfix (3.5.7) to correct the umbrella header imports.

We are sorry that we took so long to answer.

Best regards,
